import React from "react";
import SecNavBar from "../../components/SecNavBar/SecNavBar";
import { MinimalFooter } from "../../containers";
import ReactPlayer from "react-player/lazy";
import "./Tutorials.css";
export default function Tutorials() {
  return (
    <div className="Tutorials">
      <SecNavBar />
      <h2 className="tutorials_heading">Tutorials</h2>
      <div className="tutorials_container">
        <ReactPlayer
          url="https://www.youtube.com/embed/IxtOtPFwaIE?rel=0&modestbranding=1"
          width="300px"
          height="150px"
          controls
          light
        />
        <ReactPlayer
          url="https://www.youtube.com/embed/3cmRrQAZqRU?rel=0&modestbranding=1"
          width="300px"
          height="150px"
          controls
          light
        />
        <ReactPlayer
          url="https://www.youtube.com/embed/gWpUTLghv_0?rel=0&modestbranding=1"
          width="300px"
          height="150px"
          controls
          light
        />
        <ReactPlayer
          url="https://www.youtube.com/embed/wgXefCprLm0?rel=0&modestbranding=1"
          width="300px"
          height="150px"
          controls
          light
        />
        <ReactPlayer
          url="https://www.youtube.com/embed/yVE4XXFFO70?rel=0&modestbranding=1"
          width="300px"
          height="150px"
          controls
          light
        />
        <ReactPlayer
          url="https://www.youtube.com/embed/_oixJ56znyU?rel=0&modestbranding=1"
          width="300px"
          height="150px"
          controls
          light
        />
        <ReactPlayer
          url="https://www.youtube.com/embed/_NNnowkcIqU?rel=0&modestbranding=1"
          width="300px"
          height="150px"
          controls
          light
        />
        <ReactPlayer
          url="https://www.youtube.com/embed/RG4PwUP5njo?rel=0&modestbranding=1"
          width="300px"
          height="150px"
          controls
          light
        />
        <ReactPlayer
          url="https://www.youtube.com/embed/pVmOOluGAv8?rel=0&modestbranding=1"
          width="300px"
          height="150px"
          controls
          light
        />
        <ReactPlayer
          url="https://www.youtube.com/embed/4Tbp3NydcbQ?rel=0&modestbranding=1"
          width="300px"
          height="150px"
          controls
          light
        />
        <ReactPlayer
          url="https://www.youtube.com/embed/7Xl-TNyOJec?rel=0&modestbranding=1"
          width="300px"
          height="150px"
          controls
          light
        />
        <ReactPlayer
          url="https://www.youtube.com/embed/B6tb4TncKhY?rel=0&modestbranding=1"
          width="300px"
          height="150px"
          controls
          light
        />
        <ReactPlayer
          url="https://www.youtube.com/embed/NnbvPeAIhmA?rel=0&modestbranding=1"
          width="300px"
          height="150px"
          controls
          light
        />
        <ReactPlayer
          url="https://www.youtube.com/embed/EC7RGJ975iM?rel=0&modestbranding=1"
          width="300px"
          height="150px"
          controls
          light
        />
        <ReactPlayer
          url="https://www.youtube.com/embed/_xKgCrr_n9g?rel=0&modestbranding=1"
          width="300px"
          height="150px"
          controls
          light
        />
        <ReactPlayer
          url="https://www.youtube.com/embed/csErxVR7dpA?rel=0&modestbranding=1"
          width="300px"
          height="150px"
          controls
          light
        />
        <ReactPlayer
          url="https://www.youtube.com/embed/ykJmrZ5v0Oo?rel=0&modestbranding=1"
          width="300px"
          height="150px"
          controls
          light
        />
        <ReactPlayer
          url="https://www.youtube.com/embed/J_OQDNM8gn8?rel=0&modestbranding=1"
          width="300px"
          height="150px"
          controls
          light
        />
        <ReactPlayer
          url="https://www.youtube.com/embed/YFRh8TWjPZ0?rel=0&modestbranding=1"
          width="300px"
          height="150px"
          controls
          light
        />
        <ReactPlayer
          url="https://www.youtube.com/embed/3XDriUn0udo?rel=0&modestbranding=1"
          width="300px"
          height="150px"
          controls
          light
        />
        <ReactPlayer
          url="https://www.youtube.com/embed/tlUg1DXhHm8?rel=0&modestbranding=1"
          width="300px"
          height="150px"
          controls
          light
        />
        <ReactPlayer
          url="https://www.youtube.com/embed/YaXPRqUwItQ?rel=0&modestbranding=1"
          width="300px"
          height="150px"
          controls
          light
        />
        <ReactPlayer
          url="https://www.youtube.com/embed/m9me06UBPKc?rel=0&modestbranding=1"
          width="300px"
          height="150px"
          controls
          light
        />
        <ReactPlayer
          url="https://www.youtube.com/embed/QWOY17an9yQ?rel=0&modestbranding=1"
          width="300px"
          height="150px"
          controls
          light
        />
      </div>
      <MinimalFooter />
    </div>
  );
}
